// <auto-generated />
using System;
using DesignSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304212723_FixDateTimeOffsetForSqlite")]
    partial class FixDateTimeOffsetForSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DesignSystem.Domain.Entities.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GenerationSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccasionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccasionType");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.BackgroundLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeightMm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectSlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextZonesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WidthMm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.ToTable("BackgroundLayouts");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.DesignProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BackgroundLayoutId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportPdfPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportPsdPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportSvgPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccasionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SubjectAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAdjustmentsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundLayoutId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SubjectAssetId");

                    b.ToTable("DesignProjects");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.SubjectAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CutoutHeightPx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CutoutPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CutoutWidthPx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceBoundingBoxJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaskPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalDpi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalHeightPx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalWidthPx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubjectAssets");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.BackgroundLayout", b =>
                {
                    b.HasOne("DesignSystem.Domain.Entities.Background", "Background")
                        .WithMany("Layouts")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.DesignProject", b =>
                {
                    b.HasOne("DesignSystem.Domain.Entities.BackgroundLayout", "BackgroundLayout")
                        .WithMany()
                        .HasForeignKey("BackgroundLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignSystem.Domain.Entities.SubjectAsset", "SubjectAsset")
                        .WithMany()
                        .HasForeignKey("SubjectAssetId");

                    b.Navigation("BackgroundLayout");

                    b.Navigation("SubjectAsset");
                });

            modelBuilder.Entity("DesignSystem.Domain.Entities.Background", b =>
                {
                    b.Navigation("Layouts");
                });
#pragma warning restore 612, 618
        }
    }
}
